baseURL = 'https://blog.pilab.space'
languageCode = "en-us"
title = "Pilab Pipelines"
theme = "terminal"
relativeURLs = false
canonifyURLs = true

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = true
  centerTheme = false
  customCSS = ["css/custom.css"]

  [params.logo]
    logoText = "$ cd ~/blog"
    logoHomeLink = "/"

[module]
  [[module.mounts]]
    source = "../content"
    target = "content"
